# Generated by Django 3.0.3 on 2020-02-26 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_item_productcategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='author',
        ),
    ]
