# Generated by Django 3.0.3 on 2020-02-26 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_remove_item_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='status',
            field=models.CharField(choices=[('featured', 'Draft'), ('newproduct', 'New product'), ('inspired', 'Inspired')], default='inspired', max_length=10),
        ),
    ]
